### ISSUE TITLE
Align y-axis on left and right sides

### ISSUE THREAD

**Issue by a-becker42** [barefigures/website-issues#23]
For readability purposes, I'd suggest aligning the origin of the y-axis on the left and right sides on all graphs. This is already the case in most cases (e.g. on [Tesla Net Income](https://barefigur.es/companies/tesla-motors/net-income/)) but not in all cases, such as in [Google Net Income](https://barefigur.es/companies/google/net-income/) or [Twitter Net Income](https://barefigur.es/companies/twitter/net-income/).

That might be a question of taste, but I thought I'd just bring up the question in case you agree with me.

Thanks!

**Comment by isellsoap** [comment]
Sorry, I don’t understand the problem. Could you give me an example (e.g. screenshot) of the change you want to see? Thanks!

**Comment by a-becker42** [comment]
Sure! Here's a [screenshot](https://www.dropbox.com/s/adscak4yvunf5mw/Screenshot%20Twitter%20net%20income.png?dl=0) with the Twitter net income.

I felt it generally helps to have the "0-level" aligned on both sides of the graph, like in [Google Revenues](https://barefigur.es/companies/google/revenues/).

Does this help?

**Comment by isellsoap** [comment]
Now I get what you mean. I found [this SO thread](http://stackoverflow.com/questions/16086049/how-can-i-force-multiple-y-axis-in-highcharts-to-have-a-common-zero) and [this Highcharts feature request](http://highcharts.uservoice.com/forums/55896-general/suggestions/2554384-multiple-axis-alignment-control) discussing the same issue. I personally don’t see a problem in that, since the two axes are completely different things semantically speaking and therefor they don’t have to be on the same level. The alignment of the two axes happens automatically by [Highcharts](http://www.highcharts.com/), the chart rendering tool I use on the site.

Thanks for opening the issue, but I think I won’t add this feature. Looks also rather complicated to implement it technically.
